export const GET_ERRORS="GET_ERRORS";
export const GET_TASKS="GET_TASKS";
export const DELETE="DELETE";
export const GET_TASK_DETAILS="GET_TASK_DETAILS";
export const GET_USER_DETAILS="GET_USER_DETAILS";
export const VALID_USER = "VALID_USER";
export const INVALID_USER = "INVALID_USER";
export const LOGOUT = "LOGOUT";
export const MESSAGE = "MESSAGE";
